ALTER TABLE "paymentIntent"
  ADD COLUMN IF NOT EXISTS "feeKobo" BIGINT NOT NULL DEFAULT 0;

ALTER TABLE "Withdrawal"
  ADD COLUMN IF NOT EXISTS "feeKobo" BIGINT NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "estimatedCostKobo" BIGINT NOT NULL DEFAULT 0;
